export const EVIDENCE_POLICY_VERSION = "0.1"
export const CONFIDENCE_FORMULA_VERSION = "0.1"
export const FRESHNESS_POLICY_VERSION = "0.1"

export const CLEARED_MIN_CONFIDENCE = 85
export const CONFLICT_SCORE_CAP = 39
export const RETRIEVAL_MAX_AGE_DAYS = 7
export const REGISTRY_REFRESH_MAX_AGE_DAYS = 7
export const CURRENT_CLAIM_MAX_AGE_MONTHS = 6
